title: hello world
description: Blog
author: evttenorio
#github: https://github.com/evttenorio
about: Estudade de Sistemas de InformaÃ§Ã£o tentando falar sobre Linux e Python, ou qualquer coisa do tipo. ğŸ‘¨â€ğŸ’» ğŸ‘¾	
disqus_shortname: evttenorio
google_analytics: brr-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-linkedin
#     link: "#"
#   - icon: fa-github
#     link: "#"
#    - icon: fa-facebook
#      link: "#"
#    - icon: fa-twitter
#      link: "#"
#    - icon: fa-stack-exchange
#      link: "#"


share:
  twitter_username: d85421dtenorio
#  fb_appid: 1749788565247320xxxx

urls:
    - text: Sobre mim
      url: /about/
 #   - text: My Projects
 #     url: /projects/
 #   - text: XML Feed
 #     url: /feed.xml

url: "https://tenoriorazr.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
