title: hello world
description: ConteÃºdos, opiniÃµes e notas sobre tecnologias, Sistemas Operacionais (Linux e Windows) e Python.
author: Everton T.
#github: https://github.com/evttenorio
about: Estudante de SI comentando sobre Linux e Python, ou qualquer coisa do tipo. ðŸ˜Ž	
disqus_shortname: evttenorio
google_analytics: G-KNKVW805PE

enableTags: true
tagarray: [linux, windows, seguranÃ§a, python]

collections:
  project:
    output: true
    permalink: /project/:path/

social:
#    - icon: fa-linkedin
#     link: "#"
#   - icon: fa-github
#     link: "https://github.com/evttenorio"
#    - icon: fa-facebook
#      link: "#"
#    - icon: fa-twitter
#      link: "#"
#    - icon: fa-stack-exchange
#      link: "#"


share:
  twitter_username: d85421dtenorio
#  fb_appid: 1749788565247320xxxx

urls:
    - text: Sobre mim
      url: /about/
 #   - text: My Projects
 #     url: /projects/
 #   - text: XML Feed
 #     url: /feed.xml

url: "https://tenoriorazr.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: GFM
#kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
